#!/bin/bash

set -e

. utils/common

# Needed for disk injection direct into images
# TODO: Can we just use config drive and deprecate this
#apt-get install --yes guestmount

# TODO: At boot?
modprobe nbd
apt-get install --yes kpartx


mkdir -p /var/openstack/compute
mkdir -p /var/log/openstack
mkdir -p /var/openstack/compute/instances

# Build generic compute config file
# TODO: Can we set this up so that we can override it?
cat > /var/openstack/compute/compute.conf << EOF
[DEFAULT]
verbose=True
instances_path=/var/openstack/compute/instances
auth_strategy=keystone
allow_resize_to_same_host=True
root_helper=sudo /opt/openstack/nova/bin/nova-rootwrap
compute_scheduler_driver=nova.scheduler.filter_scheduler.FilterScheduler
dhcpbridge_flagfile=/etc/openstack/compute.conf
fixed_range=${NETWORK_RANGE}
s3_host=${HEAD_IP}
network_manager=nova.network.manager.FlatManager
volume_group=nova-volumes
volume_name_template=volume-%08x
iscsi_helper=tgtadm
osapi_compute_extension=nova.api.openstack.compute.contrib.standard_extensions
my_ip=${MY_IP}
public_interface=${BRIDGE_INTERFACE}
vlan_interface=${NETWORK_INTERFACE}
flat_network_bridge=${BRIDGE_INTERFACE}
flat_interface=${NETWORK_INTERFACE}
sql_connection=postgresql://openstack_compute:${DB_PASSWORD_COMPUTE}@${HEAD_IP}/openstack_compute
libvirt_type=kvm
instance_name_template=instance-%08x
novncproxy_base_url=http://${HEAD_IP}:6080/vnc_auto.html
xvpvncproxy_base_url=http://${HEAD_IP}:6081/console
vncserver_listen=127.0.0.1
vncserver_proxyclient_address=127.0.0.1
api_paste_config=/var/openstack/compute/api-paste.ini
image_service=nova.image.glance.GlanceImageService
ec2_dmz_host=${HEAD_IP}
rabbit_host=${HEAD_IP}
rabbit_password=${RABBIT_PASSWORD}
glance_api_servers=${HEAD_IP}:9292
force_dhcp_release=True
flat_injected=True
connection_type=libvirt
firewall_driver=nova.virt.libvirt.firewall.IptablesFirewallDriver
EOF


cp /opt/openstack/nova/etc/nova/api-paste.ini /var/openstack/compute/

utils/openstack-config-set /var/openstack/compute/api-paste.ini "filter:authtoken" admin_tenant_name $SERVICE_TENANT_NAME
utils/openstack-config-set /var/openstack/compute/api-paste.ini "filter:authtoken" admin_user $NOVA_SERVICE_USERNAME
utils/openstack-config-set /var/openstack/compute/api-paste.ini "filter:authtoken" admin_password $NOVA_SERVICE_PASSWORD

export PYTHONPATH="/opt/openstack/python-novaclient/:/opt/openstack/glance/"

pushd /opt/openstack/python-novaclient/
python setup.py develop
popd

# Create database / bring schema up to date
pushd /opt/openstack/nova
bin/nova-manage --conf /var/openstack/compute/compute.conf db sync 

popd

for s in openstack-compute-api openstack-compute-scheduler openstack-compute-network openstack-compute-cpu openstack-compute-console openstack-compute-novnc
do
	cp supervisor/${s}.conf /etc/supervisor/conf.d/
	supervisorctl update ${s}
	supervisorctl restart ${s}
done

supervisorctl status

