#!/bin/bash

. utils/common

apt-get install --yes postgresql-9.1 

# TODO: We need to open to the private network (not just 127.0.0.1)
sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/" /etc/postgresql/9.1/main/postgresql.conf 
cat >> /etc/postgresql/9.1/main/pg_hba.conf <<EOF
# Accept all IPv4 connections
host    all         all         0.0.0.0/0             md5
EOF

/etc/init.d/postgresql restart

su -c "psql -c 'CREATE DATABASE openstack_compute'" postgres
su -c "psql -c \"CREATE USER openstack_compute WITH PASSWORD '${DB_PASSWORD_COMPUTE}'\"" postgres
su -c "psql -c 'GRANT ALL PRIVILEGES ON DATABASE openstack_compute TO openstack_compute'" postgres

su -c "psql -c 'CREATE DATABASE openstack_imagestore'" postgres
su -c "psql -c \"CREATE USER openstack_imagestore WITH PASSWORD '${DB_PASSWORD_IMAGESTORE}'\"" postgres
su -c "psql -c 'GRANT ALL PRIVILEGES ON DATABASE openstack_imagestore TO openstack_imagestore'" postgres

su -c "psql -c 'CREATE DATABASE openstack_identity'" postgres
su -c "psql -c \"CREATE USER openstack_identity WITH PASSWORD '${DB_PASSWORD_IDENTITY}'\"" postgres
su -c "psql -c 'GRANT ALL PRIVILEGES ON DATABASE openstack_identity TO openstack_identity'" postgres

