#!/bin/bash

mkdir -p /var/openstack/identity
mkdir -p /var/log/openstack
mkdir -p /var/log/openstack/identity

DB_PASSWORD_IDENTITY=`utils/openstack-config-get /etc/openstack/openstack.conf secrets identity_db_password`

DB_CONNECTION="postgresql://openstack_identity:${DB_PASSWORD_IDENTITY}@localhost/openstack_identity"

cp /opt/openstack/keystone/etc/keystone.conf /var/openstack/identity/identity.conf
cp /opt/openstack/keystone/etc/policy.json /var/openstack/identity

utils/openstack-config-set /var/openstack/identity/identity.conf sql connection $DB_CONNECTION

# TODO: Should we use SQL?
cp /opt/openstack/keystone/etc/default_catalog.templates /var/openstack/identity/
sed -i "s/localhost/${HEAD_IP}/g" /var/openstack/identity/default_catalog.templates

utils/openstack-config-set /var/openstack/identity/identity.conf catalog template_file /var/openstack/identity/default_catalog.templates


# Create database / bring schema up to date
pushd /opt/openstack/keystone
bin/keystone-manage --conf /var/openstack/identity/identity.conf db_sync
popd


# Create system tenants etc
export SERVICE_ENDPOINT=`utils/openstack-config-get /etc/openstack/openstack.conf identity endpoint --default http://127.0.0.1:35357/v2.0/`
export SERVICE_TOKEN=`utils/openstack-config-get /etc/openstack/openstack.conf secrets identity_service_token`

SERVICE_TENANT_NAME=`utils/openstack-config-get /etc/openstack/openstack.conf secrets service_tenant_name --default services`

keystone tenant-create --name ${SERVICE_TENANT_NAME}

# Default roles
keystone role-create --name=admin
keystone role-create --name=KeystoneAdmin
keystone role-create --name=KeystoneServiceAdmin

#keystone tenant-create --name admin
#keystone user-create --name=admin --pass=supersecret
#keystone user-role-add --user admin --role admin --tenant_id admin --byname true

# Configure service users/roles
NOVA_SERVICE_USERNAME=`utils/openstack-config-get /etc/openstack/openstack.conf secrets compute_service_username --default nova`
NOVA_SERVICE_PASSWORD=`utils/openstack-config-get /etc/openstack/openstack.conf secrets compute_service_password`
keystone user-create --name=$NOVA_SERVICE_USERNAME --pass="$NOVA_SERVICE_PASSWORD" --tenant_id $SERVICE_TENANT_NAME --byname true
keystone user-role-add --tenant_id $SERVICE_TENANT_NAME --user $NOVA_SERVICE_USERNAME --role admin --byname true

GLANCE_SERVICE_USERNAME=`utils/openstack-config-get /etc/openstack/openstack.conf secrets imagestore_service_username --default glance`
GLANCE_SERVICE_PASSWORD=`utils/openstack-config-get /etc/openstack/openstack.conf secrets imagestore_service_password`
keystone user-create --name=$GLANCE_SERVICE_USERNAME --pass="$GLANCE_SERVICE_PASSWORD" --tenant_id $SERVICE_TENANT_NAME --byname true
keystone user-role-add --tenant_id $SERVICE_TENANT_NAME --user $GLANCE_SERVICE_USERNAME --role admin --byname true



cp supervisor/openstack-identity.conf /etc/supervisor/conf.d/

supervisorctl update openstack-identity

