#!/bin/bash

mkdir -p /var/openstack/imagestore/conf
mkdir -p /var/log/openstack

cp /opt/openstack/glance/etc/* /var/openstack/imagestore/conf

# Force logging to go to stdout (so we don't have two log files)
utils/openstack-config-set /var/openstack/imagestore/conf/glance-api.conf DEFAULT use_syslog False
utils/openstack-config-set /var/openstack/imagestore/conf/glance-api.conf DEFAULT log_file ""

utils/openstack-config-set /var/openstack/imagestore/conf/glance-registry.conf DEFAULT use_syslog False
utils/openstack-config-set /var/openstack/imagestore/conf/glance-registry.conf DEFAULT log_file ""

# Repoint the policy.json file so we don't have to install it in /etc/glance
utils/openstack-config-set /var/openstack/imagestore/conf/glance-api.conf DEFAULT policy_file /var/openstack/imagestore/conf/policy.json
utils/openstack-config-set /var/openstack/imagestore/conf/glance-registry.conf DEFAULT policy_file /var/openstack/imagestore/conf/policy.json

DB_PASSWORD_IMAGESTORE=`utils/openstack-config-get /etc/openstack/openstack.conf secrets imagestore_db_password`
DB_CONNECTION="postgresql://openstack_imagestore:${DB_PASSWORD_IMAGESTORE}@localhost/openstack_imagestore"

utils/openstack-config-set /var/openstack/imagestore/conf/glance-registry.conf DEFAULT sql_connection $DB_CONNECTION

utils/openstack-config-set /var/openstack/imagestore/conf/glance-api.conf paste_deploy flavor keystone
utils/openstack-config-set /var/openstack/imagestore/conf/glance-registry.conf paste_deploy flavor keystone

utils/openstack-config-set /var/openstack/imagestore/conf/glance-api.conf DEFAULT debug True
utils/openstack-config-set /var/openstack/imagestore/conf/glance-registry.conf DEFAULT debug True

SERVICE_TENANT_NAME=`utils/openstack-config-get /etc/openstack/openstack.conf secrets service_tenant_name --default services`
SERVICE_USER=`utils/openstack-config-get /etc/openstack/openstack.conf secrets imagestore_service_username --default glance`
SERVICE_PASSWORD=`utils/openstack-config-get /etc/openstack/openstack.conf secrets imagestore_service_password`

# Modified from devstack
function glance_config {
    sed -e "
        s,%SERVICE_TENANT_NAME%,$SERVICE_TENANT_NAME,g;
        s,%SERVICE_USER%,$SERVICE_USER,g;
        s,%SERVICE_PASSWORD%,$SERVICE_PASSWORD,g;
    " -i $1
}

glance_config /var/openstack/imagestore/conf/glance-api.conf
glance_config /var/openstack/imagestore/conf/glance-api-paste.ini
glance_config /var/openstack/imagestore/conf/glance-registry.conf
glance_config /var/openstack/imagestore/conf/glance-registry-paste.ini

cp supervisor/openstack-imagestore-registry.conf /etc/supervisor/conf.d/
supervisorctl update openstack-imagestore-registry

cp supervisor/openstack-imagestore-api.conf /etc/supervisor/conf.d/
supervisorctl update openstack-imagestore-api

supervisorctl status

