#!/bin/bash

RABBIT_PASSWORD=`utils/openstack-config-get /etc/openstack/openstack.conf secrets rabbitmq_password`

apt-get install --yes rabbitmq-server

sudo rabbitmqctl change_password guest ${RABBIT_PASSWORD}

