#!/bin/bash

# Load settings
HEAD_IP=`utils/openstack-config-get /etc/openstack/openstack.conf network head_node`
KEYSTONE_IP=${HEAD_IP}

SERVICE_TENANT_NAME=`utils/openstack-config-get /etc/openstack/openstack.conf secrets service_tenant_name --default services`
SERVICE_USER=`utils/openstack-config-get /etc/openstack/openstack.conf secrets compute_service_username --default swift`
SERVICE_PASSWORD=`utils/openstack-config-get /etc/openstack/openstack.conf secrets objectstore_service_password`
SERVICE_TOKEN=`utils/openstack-config-get /etc/openstack/openstack.conf secrets identity_service_token`

# TODO: Ensure objectstore-common


#==============================================================================
# I think we need to install swift??
pushd /opt/openstack/swift
python setup.py install
popd

#==============================================================================
# Dependencies
apt-get install --yes memcached

#==============================================================================

mkdir -p /var/openstack/objectstore/

cp /opt/openstack/swift/etc/proxy-server.conf-sample /var/openstack/objectstore/proxy-server.conf

# SSL?
#utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT cert_file /etc/swift/cert.crt
#utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT key_file /etc/swift/cert.key

utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT swift_dir /var/openstack/objectstore/config

utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT bind_port 8080
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT workers 8
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT user swift

utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT log_level DEBUG
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT log_facility LOG_LOCAL0
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf DEFAULT log_name swift



# Use keystone auth
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "pipeline:main" pipeline "catch_errors healthcheck cache ratelimit s3token tokenauth keystone proxy-server"

# ???
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "app:proxy-server" allow_account_management true
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "app:proxy-server" account_autocreate true

# filter:keystone
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:keystone" "paste.filter_factory" "keystone.middleware.swift_auth:filter_factory"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:keystone" "operator_roles"  "Member,admin"

# filter:s3token
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:s3token" "paste.filter_factory"  "keystone.middleware.s3_token:filter_factory"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:s3token" "auth_host"  ${KEYSTONE_IP}
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:s3token" "auth_port"  "35357"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:s3token" "auth_protocol"  "http"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:s3token" "admin_token"  "${SERVICE_TOKEN}"

# filter:tokenauth
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "paste.filter_factory"  "keystone.middleware.auth_token:filter_factory"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "cache"  "swift.cache"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "auth_host"  ${KEYSTONE_IP}
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "auth_port"  "35357"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "auth_protocol"  "http"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "admin_tenant_name"  "${SERVICE_TENANT_NAME}"
#utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "admin_user"  "${SERVICE_USER}"
#utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "admin_password"  "${SERVICE_PASSWORD}"
utils/openstack-config-set /var/openstack/objectstore/proxy-server.conf "filter:tokenauth" "admin_token"  "${SERVICE_TOKEN}"


# Service
cp supervisor/openstack-objectstore-proxy.conf /etc/supervisor/conf.d/
supervisorctl update openstack-objectstore-proxy
supervisorctl restart openstack-objectstore-proxy

supervisorctl status


