#!/bin/bash

# TODO: set -e 

. utils/common

# Load settings
KEYSTONE_IP=${HEAD_IP}

SWIFT_HASH_SECRET=`utils/openstack-config-get /etc/openstack/openstack.conf secrets swift_hash_path_suffix`

#==============================================================================
# Directories
mkdir -p /var/openstack/objectstore/
mkdir -p /var/openstack/objectstore/config

mkdir -p /var/openstack/objectstore/data/


# TODO: Is there any way to just log to a file??
#==============================================================================
# Syslog
cp files/etc/rsyslog.d/openstack-storage.conf /etc/rsyslog.d/
# Do we need e.g. /etc/init.d/rsyslog reload


#==============================================================================
# Swift Unix user/group

addgroup swift
adduser --quiet  --system --no-create-home --disabled-password --ingroup swift swift

# TODO: Should group be openstack
# TODO: Should user be objstore ?
chown -R swift:swift /var/openstack/objectstore/data/


#==============================================================================
# General config
# TODO: /etc/swift/swift.conf is hard-coded??
mkdir -p /etc/swift
touch /var/openstack/objectstore/swift.conf
ln -s /var/openstack/objectstore/swift.conf /etc/swift/

utils/openstack-config-set /var/openstack/objectstore/swift.conf "swift-hash" swift_hash_path_suffix ${SWIFT_HASH_SECRET}

