#!/bin/bash -x

set -e

. utils/common

# Create system tenants etc
export SERVICE_ENDPOINT=$IDENTITY_SERVICE_ENDPOINT
export SERVICE_TOKEN=$IDENTITY_SERVICE_TOKEN

export PYTHONPATH=/opt/openstack/python-keystoneclient

# TODO: keystone should just take usernames
function get_id() {
        keystone $1-list | grep $2 |  awk ' { print $2 }'
}

function create_tenant() {
	keystone tenant-create --name $1 || true
	get_id tenant $1
}

function create_role() {
	keystone role-create --name $1 || true
	get_id role $1
}

function create_user() {
	keystone user-create --name $1 --pass $2 --tenant_id $3 || true
	get_id user $1
}

function add_user_to_role() {
	keystone user-role-add --tenant_id $1 --user $2 --role $3 || true
}

SERVICE_TENANT_ID=$(create_tenant ${SERVICE_TENANT_NAME})

# Default roles
ADMIN_ID=$(create_role admin)
KEYSTONE_ADMIN_ID=$(create_role KeystoneAdmin)
KEYSTONE_SERVICE_ADMIN_ID=$(create_role KeystoneServiceAdmin)

# Configure service users/roles
NOVA_ID=$(create_user $NOVA_SERVICE_USERNAME "$NOVA_SERVICE_PASSWORD" $SERVICE_TENANT_ID)
add_user_to_role $SERVICE_TENANT_ID $NOVA_ID $ADMIN_ID

GLANCE_ID=$(create_user $GLANCE_SERVICE_USERNAME "$GLANCE_SERVICE_PASSWORD" $SERVICE_TENANT_ID)
add_user_to_role $SERVICE_TENANT_ID $GLANCE_ID $ADMIN_ID


REGION=privatecloud

function create_endpoint() {
# TODO: Make this idempotent
keystone service-create --name=$1 \
                       --type=$2 \
                        --description="$3"

SERVICE_ID=$(get_id service $1)

# TODO: How to make this idempotent??
keystone endpoint-create --region ${REGION} --service_id $SERVICE_ID \
        --publicurl "$4" \
        --adminurl "$4" \
        --internalurl "$4"
}

ENDPOINT="http://"${HEAD_IP}':$(compute_port)s/v1.1/$(tenant_id)s'
create_endpoint "nova" "compute" "Compute Service" "${ENDPOINT}"

ENDPOINT="http://"${HEAD_IP}':8773/services/Cloud'
create_endpoint "ec2" "ec2" "Compute Legacy Cloud (EC2) compatability" "${ENDPOINT}"

ENDPOINT="http://"${HEAD_IP}':9292/v1'
create_endpoint "glance" "image" "Image Store" "${ENDPOINT}"

ENDPOINT="http://"${HEAD_IP}':8080/v1/AUTH_$(tenant_id)s'
create_endpoint "swift" "object-store" "Object Store" "${ENDPOINT}"

ENDPOINT="http://"${HEAD_IP}':$(public_port)s/v2.0'
create_endpoint "keystone" "identity" "Identity Service" "${ENDPOINT}"

ENDPOINT="http://"${HEAD_IP}':8776/v1/$(tenant_id)s'
create_endpoint "nova-volume" "volume" "Volume Service" "${ENDPOINT}"



