#!/bin/bash 

#====================================
# Begin boilerplate
set -e

PRG="$0"
while [ -h "$PRG" ] ; do
   PRG=`readlink "$PRG"`
done

pushd `dirname $PRG` > /dev/null
cd ..
BASEDIR=`pwd`
popd > /dev/null

# End boilerplate
#====================================

ADD_IP=$1

if [[ "${ADD_IP}" = "" ]]; then
	echo "Must specify IP to add"
	exit 1
fi


UTILSDIR=${BASEDIR}/utils/
HELPERSDIR=${UTILSDIR}/helpers/

CLOUD_CONF_FILE=${BASEDIR}/localconf/openstack.conf

. ${HELPERSDIR}/load-cloudconfig

if [[ "${HEAD_IP}" = "" ]]; then
	echo "Must specify HEAD_IP"
	exit 1
fi

HEAD_CONF_FILE=${BASEDIR}/localconf/${HEAD_IP}.conf
MACHINE_CONF_FILE=${BASEDIR}/localconf/${ADD_IP}.conf

DEFAULT_CONF_FILE=${HEAD_CONF_FILE}

if [[ -e ${MACHINE_CONF_FILE} ]]; then
	DEFAULT_CONF_FILE=${MACHINE_CONF_FILE}
fi

if [[ "${BRIDGE_INTERFACE}" = "" ]]; then
	# Assume same bridge
	BRIDGE_INTERFACE=`${UTILSDIR}/openstack-config-get ${DEFAULT_CONF_FILE} network bridge_interface`
fi

if [[ "${NETWORK_INTERFACE}" = "" ]]; then
	# Assume same interface
	NETWORK_INTERFACE=`${UTILSDIR}/openstack-config-get ${DEFAULT_CONF_FILE} network network_interface`
fi

utils/openstack-config-set ${MACHINE_CONF_FILE} network bridge_interface ${BRIDGE_INTERFACE}
utils/openstack-config-set ${MACHINE_CONF_FILE} network my_ip ${ADD_IP}
utils/openstack-config-set ${MACHINE_CONF_FILE} network network_interface ${NETWORK_INTERFACE}

