#!/bin/bash 

set -e

if [[ "${HEAD_IP}" = "" ]]; then
	echo "Must specify HEAD_IP"
	exit 1
fi

if [[ "${MY_IP}" = "" ]]; then
	echo "Must specify MY_IP"
	exit 1
fi

if [[ "${NETWORK_RANGE}" = "" ]]; then
	echo "Must specify NETWORK_RANGE"
	exit 1
fi

if [[ "${CLOUD_RANGE}" = "" ]]; then
	echo "Must specify CLOUD_RANGE"
	exit 1
fi

if [[ "${NETWORK_INTERFACE}" = "" ]]; then
	echo "Must specify NETWORK_INTERFACE"
	exit 1
fi

if [[ "${NETWORK_GATEWAY}" = "" ]]; then
	echo "Must specify NETWORK_GATEWAY"
	exit 1
fi

if [[ "${BRIDGE_INTERFACE}" = "" ]]; then
	BRIDGE_INTERFACE=br100
fi

utils/openstack-config-set /etc/openstack/openstack.conf network head_node ${HEAD_IP}
utils/openstack-config-set /etc/openstack/openstack.conf network cloud_range ${CLOUD_RANGE}
utils/openstack-config-set /etc/openstack/openstack.conf network network_range ${NETWORK_RANGE}
utils/openstack-config-set /etc/openstack/openstack.conf network gateway ${NETWORK_GATEWAY}

utils/openstack-config-set /etc/openstack/machine.conf network bridge_interface ${BRIDGE_INTERFACE}
utils/openstack-config-set /etc/openstack/machine.conf network my_ip ${MY_IP}
utils/openstack-config-set /etc/openstack/machine.conf network network_interface ${NETWORK_INTERFACE}
 
utils/generate-secrets

DB_PASSWORD_COMPUTE=`utils/openstack-config-get /etc/openstack/openstack.conf secrets compute_db_password`
RABBIT_PASSWORD=`utils/openstack-config-get /etc/openstack/openstack.conf secrets rabbitmq_password`

mkdir -p /etc/openstack/



