#!/bin/bash 

set -e

. utils/common

cat << EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ${BRIDGE_INTERFACE}
iface ${BRIDGE_INTERFACE} inet static
        bridge_ports ${NETWORK_INTERFACE}
        bridge_stp off
        bridge_maxwait 0
        bridge_fd 0
        address ${MY_IP}
        netmask ${NETWORK_RANGE_NETMASK}
        gateway ${NETWORK_GATEWAY}
EOF


