#!/bin/bash 

#====================================
# Begin boilerplate
set -e

PRG="$0"
while [ -h "$PRG" ] ; do
   PRG=`readlink "$PRG"`
done

pushd `dirname $PRG` > /dev/null
BASEDIR=`pwd`
popd > /dev/null

${BASEDIR}/utils/common

# End boilerplate
#====================================

cat << EOF
# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto ${BRIDGE_INTERFACE}
iface ${BRIDGE_INTERFACE} inet static
        bridge_ports ${NETWORK_INTERFACE}
        bridge_stp off
        bridge_maxwait 0
        bridge_fd 0
        address ${MY_IP}
        netmask ${NETWORK_RANGE_NETMASK}
        gateway ${NETWORK_GATEWAY}
EOF


