#!/bin/bash


#====================================
# Begin boilerplate
set -e

PRG="$0"
while [ -h "$PRG" ] ; do
   PRG=`readlink "$PRG"`
done

pushd `dirname $PRG` > /dev/null
cd ..
BASEDIR=`pwd`
popd > /dev/null

. ${BASEDIR}/utils/helpers/functions

# End boilerplate
#====================================


# Python modules
apt-get install --yes python-netaddr python-eventlet python-iso8601 python-lockfile python-webob python-crypto python-paste python-pastedeploy python-routes python-httplib2 python-sqlalchemy python-migrate python-kombu python-psycopg2 python-bcrypt python-passlib python-lxml python-boto python-libvirt python-cheetah python-prettytable python-numpy

# Swift python modules (?)
apt-get install --yes python-netifaces python-simplejson  python-xattr

# sudo is needed for some compute commands
apt-get install --yes sudo

# We need some modules for utils
apt-get install --yes python-iniparse

apt-get install --yes supervisor

# Virtualization support
apt-get install --yes libvirt-bin kvm

# For disk config drive. 
apt-get install --yes dosfstools


