#!/bin/bash

apt-get install --yes git

mkdir -p /opt/openstack

pushd /opt/openstack

# Grab the source code for anything we can lay our hands on
git clone https://github.com/openstack/nova.git
git clone https://github.com/openstack/glance.git
git clone https://github.com/openstack/swift.git
git clone https://github.com/openstack/keystone.git
git clone https://github.com/openstack/horizon.git
git clone https://github.com/openstack/python-novaclient.git
git clone https://github.com/openstack/python-keystoneclient.git
git clone https://github.com/cloudbuilders/noVNC.git

popd


# Python modules
apt-get install --yes python-netaddr python-eventlet python-iso8601 python-lockfile python-webob python-crypto python-paste python-pastedeploy python-routes python-httplib2 python-sqlalchemy python-migrate python-kombu python-psycopg2 python-bcrypt python-passlib python-lxml python-boto python-libvirt python-cheetah python-prettytable python-numpy

# We need some modules for utils
apt-get install --yes python-iniparse

apt-get install --yes supervisor

# Virtualization support
apt-get install --yes libvirt-bin kvm

# For disk config drive. 
apt-get install --yes dosfstools


