#!/usr/bin/env python
# vim: tabstop=4 shiftwidth=4 softtabstop=4

import argparse
import iniparse
import re
import sys

parser = argparse.ArgumentParser()
parser.add_argument('templatefile')
parser.add_argument('configsection')
parser.add_argument('configfile')

args = parser.parse_args()

config = iniparse.ConfigParser()
config.read(args.configfile)

find_subs = re.compile(r'\%([^%]*)\%')

def process_match(match):
    key = match.group(1)
    try:
        value = config.get(args.section, key)
    except iniparse.NoOptionError:
        value = None
    return value

def replace_line(line):
    line = find_subs.sub(process_match, line)
    return line

with open(args.templatefile, 'r') as f:
    for line in f:
        line = replace_line(line)
        print line,
